public enum TokenType {
    KW_NUMBER, KW_REAL, KW_CHAR, KW_STR, KW_BOOL,
    KW_IF, KW_ELSE, KW_RETURN, KW_BREAK, KW_VOID, KW_FOR,
    ID, 
    NUMBER_LIT, REAL_LIT, CHAR_LIT, STR_LIT,
    PLUS, MINUS, MULT, DIV, MOD,
    EQ, NE, GT, GE, LT, LE, 
    AND, OR, NOT,
    ASSIGN,
    LPAREN, RPAREN, 
    LBRACE, RBRACE,
    LBRACKET, RBRACKET,
    COMMA, SEMICOLON, DOT,
    EOF
}

